# Generated by Django 2.2.4 on 2019-08-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='joined',
            field=models.DateField(null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
