# Generated by Django 2.2.4 on 2019-08-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190813_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='semillero',
            field=models.CharField(choices=[('1', 'Semillero de robotica'), ('2', 'Larrea'), ('3', 'Larrea')], max_length=100, null=True, verbose_name='Semillero'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='document',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Documento de identidad'),
        ),
    ]
