# Generated by Django 2.2.4 on 2019-08-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190813_2329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integrante',
        ),
    ]
