# Generated by Django 2.2.4 on 2019-08-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0004_delete_integrante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre del integrante')),
                ('document', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Documento de identidad')),
                ('semillero', models.CharField(choices=[('1', 'Semillero de robotica'), ('2', 'Larrea'), ('3', 'Larrea')], max_length=100, null=True, verbose_name='Semillero')),
                ('rol', models.PositiveSmallIntegerField(null=True, verbose_name='Rol')),
                ('joined', models.DateField(null=True, verbose_name='Fecha de ingreso')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico')),
                ('career', models.TextField(null=True, verbose_name='Programa de pregrado')),
                ('level', models.PositiveSmallIntegerField(null=True, verbose_name='Nivel en el programa')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['-joined'],
            },
        ),
    ]
