# Generated by Django 2.2.4 on 2019-08-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_integrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='career',
            field=models.CharField(max_length=50, null=True, verbose_name='Programa de pregrado'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='semillero',
            field=models.CharField(max_length=100, null=True, verbose_name='Semillero'),
        ),
    ]
